/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for the docs site
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Module 1: The Robotic Nervous System (ROS 2)',
      items: [
        'module-1-ros2/chapter-1-intro',
        'module-1-ros2/chapter-2-communication',
        'module-1-ros2/chapter-3-sensor-motor',
        'module-1-ros2/chapter-4-actions',
        'module-1-ros2/chapter-5-packaging',
      ],
    },
    {
      type: 'category',
      label: 'Module 2: The Digital Twin (Gazebo & Unity)',
      items: [
        'module-2-digital-twin/chapter-1-intro',
        'module-2-digital-twin/chapter-2-modeling',
        'module-2-digital-twin/chapter-3-gazebo',
        'module-2-digital-twin/chapter-4-unity',
        'module-2-digital-twin/chapter-5-full-twin',
      ],
    },
    {
      type: 'category',
      label: 'Module 3: The AI-Robot Brain (NVIDIA Isaac)',
      items: [
        'module-3-ai-brain/chapter-1-intro',
        'module-3-ai-brain/chapter-2-perception',
        'module-3-ai-brain/chapter-3-motion-planning',
        'module-3-ai-brain/chapter-4-rl',
        'module-3-ai-brain/chapter-5-ros-integration',
      ],
    },
    {
      type: 'category',
      label: 'Module 4: Vision-Language-Action (VLA)',
      items: [
        'module-4-vla/chapter-1-intro',
        'module-4-vla/chapter-2-perception',
        'module-4-vla/chapter-3-planning',
        'module-4-vla/chapter-4-acting',
        'module-4-vla/chapter-5-end-to-end',
      ],
    },
  ],
   */
};

module.exports = sidebars;